# Generated by Django 5.0.6 on 2024-08-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('machine', models.CharField(max_length=255)),
                ('proplem', models.TextField()),
                ('tel', models.CharField(max_length=12)),
            ],
        ),
    ]
